### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by hell03end** [hell03end/hse_ruz#8]
* [ ] add free auditoriums monitoring
* [x] find lecturer by name
* [ ] remove environment variables usage (`os.environ` in code)
* [ ] test request schema changes (Gid, etc.)
* [x] test all API endpoints
